package apiserver

import (
	"fmt"
	"net/http"
	"os"
	"sync"
	"testing"

	"github.com/dranih/go-crud-api/pkg/utils"
)

// Global API tests for records
// To check compatibility with php-crud-api
func TestColumnsApi(t *testing.T) {
	db_path := utils.SelectConfig(false)
	config := ReadConfig()
	config.Init()

	serverUrlHttps := fmt.Sprintf("https://%s:%d", config.Server.Address, config.Server.HttpsPort)
	if !utils.IsServerStarted(serverUrlHttps) {
		if db_path != "" && config.Api.Driver == "sqlite" {
			config.Api.Address = db_path
		}
		serverStarted := new(sync.WaitGroup)
		serverStarted.Add(1)
		api := NewApi(config)
		go api.Handle(serverStarted)
		//Waiting http server to start
		serverStarted.Wait()
	}

	//https://ieftimov.com/post/testing-in-go-testing-http-servers/
	//https://stackoverflow.com/questions/42474259/golang-how-to-live-test-an-http-server
	tt := []utils.Test{
		//Sqlite : no geometry and bigint ids
		{
			Name:   "001_get_database_A",
			Method: http.MethodGet,
			Uri:    "/columns",
			Body:   ``,
			//WantJson: `{"tables":[{"name":"barcodes","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"product_id","type":"integer","fk":"products"},{"name":"hex","type":"varchar","length":255},{"name":"bin","type":"blob"},{"name":"ip_address","type":"varchar","length":15,"nullable":true}]},{"name":"categories","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"icon","type":"blob","nullable":true}]},{"name":"comments","type":"table","columns":[{"name":"id","type":"bigint","pk":true},{"name":"post_id","type":"integer","fk":"posts"},{"name":"message","type":"varchar","length":255},{"name":"category_id","type":"integer","fk":"categories"}]},{"name":"countries","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"shape","type":"geometry"}]},{"name":"events","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"datetime","type":"timestamp","nullable":true},{"name":"visitors","type":"bigint","nullable":true}]},{"name":"kunsthåndværk","type":"table","columns":[{"name":"id","type":"varchar","length":36,"pk":true},{"name":"Umlauts ä_ö_ü-COUNT","type":"integer"},{"name":"user_id","type":"integer","fk":"users"},{"name":"invisible_id","type":"varchar","length":36,"nullable":true,"fk":"invisibles"}]},{"name":"nopk","type":"table","columns":[{"name":"id","type":"varchar","length":36}]},{"name":"post_tags","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"post_id","type":"integer","fk":"posts"},{"name":"tag_id","type":"integer","fk":"tags"}]},{"name":"posts","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"user_id","type":"integer","fk":"users"},{"name":"category_id","type":"integer","fk":"categories"},{"name":"content","type":"varchar","length":255}]},{"name":"products","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"price","type":"decimal","precision":10,"scale":2},{"name":"properties","type":"clob"},{"name":"created_at","type":"timestamp"},{"name":"deleted_at","type":"timestamp","nullable":true}]},{"name":"tag_usage","type":"view","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"count","type":"bigint"}]},{"name":"tags","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"is_important","type":"boolean"}]},{"name":"users","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"username","type":"varchar","length":255},{"name":"password","type":"varchar","length":255},{"name":"api_key","type":"varchar","length":255,"nullable":true},{"name":"location","type":"geometry","nullable":true}]}]}`,
			//Sqlite : no geometry and bigint ids
			WantJson:   `{"tables":[{"columns":[{"name":"bin","type":"blob"},{"length":255,"name":"hex","type":"varchar"},{"name":"id","pk":true,"type":"integer"},{"length":15,"name":"ip_address","nullable":true,"type":"varchar"},{"fk":"products","name":"product_id","type":"integer"}],"name":"barcodes","type":"table"},{"columns":[{"name":"icon","nullable":true,"type":"blob"},{"name":"id","pk":true,"type":"integer"},{"length":255,"name":"name","type":"varchar"}],"name":"categories","type":"table"},{"columns":[{"fk":"categories","name":"category_id","type":"integer"},{"name":"id","pk":true,"type":"integer"},{"length":255,"name":"message","type":"varchar"},{"fk":"posts","name":"post_id","type":"integer"}],"name":"comments","type":"table"},{"columns":[{"name":"id","pk":true,"type":"integer"},{"length":255,"name":"name","type":"varchar"},{"name":"shape","type":"clob"}],"name":"countries","type":"table"},{"columns":[{"name":"datetime","nullable":true,"type":"timestamp"},{"name":"id","pk":true,"type":"integer"},{"length":255,"name":"name","type":"varchar"},{"name":"visitors","nullable":true,"type":"bigint"}],"name":"events","type":"table"},{"columns":[{"name":"Umlauts ä_ö_ü-COUNT","type":"integer"},{"length":36,"name":"id","pk":true,"type":"varchar"},{"fk":"invisibles","length":36,"name":"invisible_id","nullable":true,"type":"varchar"},{"fk":"users","name":"user_id","type":"integer"}],"name":"kunsthåndværk","type":"table"},{"columns":[{"length":36,"name":"id","type":"varchar"}],"name":"nopk","type":"table"},{"columns":[{"name":"id","pk":true,"type":"integer"},{"fk":"posts","name":"post_id","type":"integer"},{"fk":"tags","name":"tag_id","type":"integer"}],"name":"post_tags","type":"table"},{"columns":[{"fk":"categories","name":"category_id","type":"integer"},{"length":255,"name":"content","type":"varchar"},{"name":"id","pk":true,"type":"integer"},{"fk":"users","name":"user_id","type":"integer"}],"name":"posts","type":"table"},{"columns":[{"name":"created_at","type":"timestamp"},{"name":"deleted_at","nullable":true,"type":"timestamp"},{"name":"id","pk":true,"type":"integer"},{"length":255,"name":"name","type":"varchar"},{"name":"price","precision":10,"scale":2,"type":"decimal"},{"name":"properties","type":"clob"}],"name":"products","type":"table"},{"columns":[{"name":"count","type":"clob"},{"name":"id","pk":true,"type":"integer"},{"length":255,"name":"name","type":"varchar"}],"name":"tag_usage","type":"view"},{"columns":[{"name":"id","pk":true,"type":"integer"},{"name":"is_important","type":"boolean"},{"length":255,"name":"name","type":"varchar"}],"name":"tags","type":"table"},{"columns":[{"length":255,"name":"api_key","nullable":true,"type":"varchar"},{"name":"id","pk":true,"type":"integer"},{"name":"location","nullable":true,"type":"clob"},{"length":255,"name":"password","type":"varchar"},{"length":255,"name":"username","type":"varchar"}],"name":"users","type":"table"}]}`,
			StatusCode: http.StatusOK,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"mysql": true, "pgsql": true, "sqlsrv": true},
		},
		{
			Name:       "001_get_database_B",
			Method:     http.MethodGet,
			Uri:        "/columns",
			Body:       ``,
			WantJson:   `{"tables":[{"name":"barcodes","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"product_id","type":"integer","fk":"products"},{"name":"hex","type":"varchar","length":255},{"name":"bin","type":"blob"},{"name":"ip_address","type":"varchar","length":15,"nullable":true}]},{"name":"categories","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"icon","type":"blob","nullable":true}]},{"name":"comments","type":"table","columns":[{"name":"id","type":"bigint","pk":true},{"name":"post_id","type":"integer","fk":"posts"},{"name":"message","type":"varchar","length":255},{"name":"category_id","type":"integer","fk":"categories"}]},{"name":"countries","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"shape","type":"geometry"}]},{"name":"events","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"datetime","type":"timestamp","nullable":true},{"name":"visitors","type":"bigint","nullable":true}]},{"name":"kunsthåndværk","type":"table","columns":[{"name":"id","type":"varchar","length":36,"pk":true},{"name":"Umlauts ä_ö_ü-COUNT","type":"integer"},{"name":"user_id","type":"integer","fk":"users"},{"name":"invisible_id","type":"varchar","length":36,"nullable":true,"fk":"invisibles"}]},{"name":"nopk","type":"table","columns":[{"name":"id","type":"varchar","length":36}]},{"name":"post_tags","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"post_id","type":"integer","fk":"posts"},{"name":"tag_id","type":"integer","fk":"tags"}]},{"name":"posts","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"user_id","type":"integer","fk":"users"},{"name":"category_id","type":"integer","fk":"categories"},{"name":"content","type":"varchar","length":255}]},{"name":"products","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"price","type":"decimal","precision":10,"scale":2},{"name":"properties","type":"clob"},{"name":"created_at","type":"timestamp"},{"name":"deleted_at","type":"timestamp","nullable":true}]},{"name":"tag_usage","type":"view","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"count","type":"bigint"}]},{"name":"tags","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"name","type":"varchar","length":255},{"name":"is_important","type":"boolean"}]},{"name":"users","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"username","type":"varchar","length":255},{"name":"password","type":"varchar","length":255},{"name":"api_key","type":"varchar","length":255,"nullable":true},{"name":"location","type":"geometry","nullable":true}]}]}`,
			StatusCode: http.StatusOK,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
		},
		{
			Name:       "002_get_barcodes_table",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes",
			Body:       ``,
			WantJson:   `{"name":"barcodes","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"product_id","type":"integer","fk":"products"},{"name":"hex","type":"varchar","length":255},{"name":"bin","type":"blob"},{"name":"ip_address","type":"varchar","length":15,"nullable":true}]}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "003_get_barcodes_id_column",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/id",
			Body:       ``,
			WantJson:   `{"name":"id","type":"integer","pk":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "004_update_barcodes_id_column_A",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/id",
			Body:       `{"name":"id2","type":"bigint"}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		//For sqlite, bigint = integer
		{
			Name:       "004_update_barcodes_id_column_B",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/id2",
			Body:       ``,
			WantJson:   `{"name":"id2","type":"integer","pk":true}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"mysql": true, "pgsql": true, "sqlsrv": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "004_update_barcodes_id_column_C",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/id2",
			Body:       ``,
			WantJson:   `{"name":"id2","type":"bigint","pk":true}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "004_update_barcodes_id_column_D",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/id2",
			Body:       `{"name":"id","type":"integer"}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "004_update_barcodes_id_column_E",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/id",
			Body:       ``,
			WantJson:   `{"name":"id","type":"integer","pk":true}`,
			StatusCode: http.StatusOK,
		},
		// No alter table for sqlite
		{
			Name:       "005_update_barcodes_product_id_nullable_A",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/product_id",
			Body:       `{"nullable":true}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "005_update_barcodes_product_id_nullable_B",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/product_id",
			Body:       ``,
			WantJson:   `{"name":"product_id","type":"integer","nullable":true,"fk":"products"}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "005_update_barcodes_product_id_nullable_C",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/product_id",
			Body:       `{"nullable":false}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "005_update_barcodes_product_id_nullable_D",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/product_id",
			Body:       ``,
			WantJson:   `{"name":"product_id","type":"integer","fk":"products"}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_A",
			Method:     http.MethodGet,
			Uri:        "/columns/events/visitors",
			Body:       ``,
			WantJson:   `{"name":"visitors","type":"bigint","nullable":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_B",
			Method:     http.MethodPut,
			Uri:        "/columns/events/visitors",
			Body:       `{"nullable":false}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_C",
			Method:     http.MethodGet,
			Uri:        "/columns/events/visitors",
			Body:       ``,
			WantJson:   `{"name":"visitors","type":"bigint"}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_D",
			Method:     http.MethodPut,
			Uri:        "/columns/events/visitors",
			Body:       `{"nullable":true}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_E",
			Method:     http.MethodGet,
			Uri:        "/columns/events/id",
			Body:       ``,
			WantJson:   `{"name":"id","type":"integer","pk":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_F",
			Method:     http.MethodPut,
			Uri:        "/columns/events/visitors",
			Body:       `{"pk":false}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_G",
			Method:     http.MethodGet,
			Uri:        "/columns/events/visitors",
			Body:       ``,
			WantJson:   `{"name":"visitors","type":"bigint","nullable":true}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_H",
			Method:     http.MethodPut,
			Uri:        "/columns/events/id",
			Body:       `{"pk":true}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "006_update_events_visitors_pk_I",
			Method:     http.MethodGet,
			Uri:        "/columns/events/id",
			Body:       ``,
			WantJson:   `{"name":"id","type":"integer","pk":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "007_update_barcodes_product_id_fk_A",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/product_id",
			Body:       `{"fk":""}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "007_update_barcodes_product_id_fk_B",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/product_id",
			Body:       ``,
			WantJson:   `{"name":"product_id","type":"integer"}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "007_update_barcodes_product_id_fk_C",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/product_id",
			Body:       `{"fk":"products"}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "007_update_barcodes_product_id_fk_D",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/product_id",
			Body:       ``,
			WantJson:   `{"name":"product_id","type":"integer","fk":"products"}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "008_update_barcodes_table_A",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes",
			Body:       `{"name":"barcodes2"}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "008_update_barcodes_table_B",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes2",
			Body:       ``,
			WantJson:   `{"name":"barcodes2","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"product_id","type":"integer","fk":"products"},{"name":"hex","type":"varchar","length":255},{"name":"bin","type":"blob"},{"name":"ip_address","type":"varchar","length":15,"nullable":true}]}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "008_update_barcodes_table_C",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes2",
			Body:       `{"name":"barcodes"}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "008_update_barcodes_table_D",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes",
			Body:       ``,
			WantJson:   `{"name":"barcodes","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"product_id","type":"integer","fk":"products"},{"name":"hex","type":"varchar","length":255},{"name":"bin","type":"blob"},{"name":"ip_address","type":"varchar","length":15,"nullable":true}]}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "009_update_barcodes_hex_type_A",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/hex",
			Body:       `{"type":"clob"}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "009_update_barcodes_hex_type_B",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/hex",
			Body:       ``,
			WantJson:   `{"name":"hex","type":"clob"}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "009_update_barcodes_hex_type_C",
			Method:     http.MethodPut,
			Uri:        "/columns/barcodes/hex",
			Body:       `{"type":"varchar","length":255}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "009_update_barcodes_hex_type_D",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/hex",
			Body:       ``,
			WantJson:   `{"name":"hex","type":"varchar","length":255}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "010_create_barcodes_table_A",
			Method:     http.MethodPost,
			Uri:        "/columns",
			Body:       `{"name":"barcodes2","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"product_id","type":"integer","fk":"products"},{"name":"hex","type":"varchar","length":255},{"name":"bin","type":"blob"},{"name":"ip_address","type":"varchar","length":15,"nullable":true}]}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "010_create_barcodes_table_B",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes2",
			Body:       ``,
			WantJson:   `{"name":"barcodes2","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"product_id","type":"integer","fk":"products"},{"name":"hex","type":"varchar","length":255},{"name":"bin","type":"blob"},{"name":"ip_address","type":"varchar","length":15,"nullable":true}]}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "010_create_barcodes_table_C",
			Method:     http.MethodDelete,
			Uri:        "/columns/barcodes2",
			Body:       ``,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "011_create_barcodes_column_A",
			Method:     http.MethodPost,
			Uri:        "/columns/barcodes",
			Body:       `{"name":"alternative_product_id","type":"integer","nullable":true,"fk":"products"}`,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "011_create_barcodes_column_B",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes/alternative_product_id",
			Body:       ``,
			WantJson:   `{"name":"alternative_product_id","type":"integer","nullable":true,"fk":"products"}`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "011_create_barcodes_column_C",
			Method:     http.MethodDelete,
			Uri:        "/columns/barcodes/alternative_product_id",
			Body:       ``,
			Want:       `true`,
			Driver:     config.Api.Driver,
			SkipFor:    map[string]bool{"sqlite": true},
			StatusCode: http.StatusOK,
		},
		{
			Name:       "012_get_invisibles_table",
			Method:     http.MethodGet,
			Uri:        "/columns/invisibles",
			Body:       ``,
			Want:       `{"code":1001,"message":"Table 'invisibles' not found"}`,
			StatusCode: http.StatusNotFound,
		},
		{
			Name:       "013_get_invisible_column",
			Method:     http.MethodGet,
			Uri:        "/columns/kunsthåndværk/invisible",
			Body:       ``,
			Want:       `{"code":1005,"message":"Column 'invisible' not found"}`,
			StatusCode: http.StatusNotFound,
		},
		{
			Name:       "014_create_types_table_A",
			Method:     http.MethodPost,
			Uri:        "/columns",
			Body:       `{"name":"types","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"integer","type":"integer"},{"name":"bigint","type":"bigint"},{"name":"varchar","type":"varchar","length":10},{"name":"decimal","type":"decimal","precision":10,"scale":4},{"name":"float","type":"float"},{"name":"double","type":"double"},{"name":"boolean","type":"boolean"},{"name":"date","type":"date"},{"name":"time","type":"time"},{"name":"timestamp","type":"timestamp"},{"name":"clob","type":"clob"},{"name":"blob","type":"blob"},{"name":"geometry","type":"geometry"}]}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "014_create_types_table_B",
			Method:     http.MethodGet,
			Uri:        "/columns/types",
			Body:       ``,
			WantJson:   `{"name":"types","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"integer","type":"integer"},{"name":"bigint","type":"bigint"},{"name":"varchar","type":"varchar","length":10},{"name":"decimal","type":"decimal","precision":10,"scale":4},{"name":"float","type":"float"},{"name":"double","type":"double"},{"name":"boolean","type":"boolean"},{"name":"date","type":"date"},{"name":"time","type":"time"},{"name":"timestamp","type":"timestamp"},{"name":"clob","type":"clob"},{"name":"blob","type":"blob"},{"name":"geometry","type":"geometry"}]}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "014_create_types_table_C",
			Method:     http.MethodPost,
			Uri:        "/records/types",
			Body:       `{"integer":3,"bigint":4,"varchar":"bcd","decimal":"2.34","float":2,"double":34.56,"boolean":false,"date":"2020-02-02","time":"23:55:59","timestamp":"2002-03-04 05:06:07","clob":"b","blob":"Yg==","geometry":"POINT(2 3)"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "014_create_types_table_D",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"integer":2,"bigint":3,"varchar":"abc","decimal":"1.23","float":1,"double":23.45,"boolean":true,"date":"1970-01-01","time":"00:00:01","timestamp":"2001-02-03 04:05:06","clob":"a","blob":"YQ==","geometry":"POINT(1 2)"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "014_create_types_table_E",
			Method:     http.MethodGet,
			Uri:        "/records/types/1",
			Body:       ``,
			WantJson:   `{"id":1,"integer":2,"bigint":3,"varchar":"abc","decimal":"1.2300","float":1,"double":23.45,"boolean":true,"date":"1970-01-01","time":"00:00:01","timestamp":"2001-02-03 04:05:06","clob":"a","blob":"YQ==","geometry":"POINT(1 2)"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "014_create_types_table_F",
			Method:     http.MethodDelete,
			Uri:        "/columns/types",
			Body:       ``,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_A",
			Method:     http.MethodPost,
			Uri:        "/columns",
			Body:       `{"name":"types","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"integer","type":"integer"},{"name":"bigint","type":"bigint"},{"name":"varchar","type":"varchar","length":10},{"name":"decimal","type":"decimal","precision":10,"scale":4},{"name":"float","type":"float"},{"name":"double","type":"double"},{"name":"boolean","type":"boolean"},{"name":"date","type":"date"},{"name":"time","type":"time"},{"name":"timestamp","type":"timestamp"},{"name":"clob","type":"clob"},{"name":"blob","type":"blob"},{"name":"geometry","type":"geometry"}]}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_B",
			Method:     http.MethodPost,
			Uri:        "/records/types",
			Body:       `{"integer":2,"bigint":3,"varchar":"abc","decimal":"1.23","float":1,"double":23.45,"boolean":true,"date":"1970-01-01","time":"00:00:01","timestamp":"2001-02-03 04:05:06","clob":"a","blob":"YQ==","geometry":"POINT(1 2)"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_C",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"boolean":null}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"boolean":"cannot be null"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_D",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"integer":" 1\n"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"integer":"illegal whitespace"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_E",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"integer":"23e"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"integer":"invalid integer"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:          "015_update_types_table_F",
			Method:        http.MethodPut,
			Uri:           "/records/types/1",
			RequestHeader: map[string]string{"Content-Type": "application/x-www-form-urlencoded"},
			Body:          `integer=23e`,
			WantJson:      `{"code":1013,"message":"Input validation failed for 'types'","details":{"integer":"invalid integer"}}`,
			StatusCode:    http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_G",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"integer":"2.3"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"integer":"invalid integer"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_H",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"integer":2.3}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"integer":"invalid integer"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_I",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"integer":"12345678901"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"integer":"invalid integer"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_J",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"bigint":"12345678901234567890"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"bigint":"invalid integer"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_K",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"varchar":"12345678901"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"varchar":"string too long"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_L",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":"-1.23"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_M",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":"1.23"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_N",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":"12.23.34"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"decimal":"invalid decimal"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_O",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":"1131313145345"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"decimal":"decimal too large"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_P",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":1.2300}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"decimal":"invalid decimal"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_Q",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":"1234567.123"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"decimal":"decimal too large"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_R",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":"123456.12345"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"decimal":"decimal too precise"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_S",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"decimal":"113131.3145345"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"decimal":"decimal too precise"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_T",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"float":"string"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"float":"invalid float"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_U",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"double":"string"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"double":"invalid float"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_V",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"boolean":-1}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"boolean":"invalid boolean"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_W",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"date":"string"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"date":"invalid date"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_X",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"time":"string"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"time":"invalid time"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_Y",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"time":"still:no:time"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"time":"invalid time"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_Z",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"time":"999:999:999"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"time":"invalid time"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_AA",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"timestamp":"string"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"timestamp":"invalid timestamp"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_AB",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"timestamp":"2001-01-01 999:999:999"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"timestamp":"invalid timestamp"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_AC",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"clob":"𠜎𠜱𠝹𠱓𠱸𠲖𠳏𠳕𠴕𠵼𠵿𠸎𠸏𠹷𠺝𠺢𠻗"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_AD",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"blob":"!"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'types'","details":{"blob":"invalid base64"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "015_update_types_table_AE",
			Method:     http.MethodPut,
			Uri:        "/records/types/1",
			Body:       `{"blob":"T8O5IGVzdCBsZSBjYWbDqSBsZSBwbHVzIHByb2NoZT8"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_AF",
			Method:     http.MethodGet,
			Uri:        "/records/types/1",
			Body:       ``,
			WantJson:   `{"id":1,"integer":2,"bigint":3,"varchar":"abc","decimal":"1.2300","float":1,"double":23.45,"boolean":true,"date":"1970-01-01","time":"00:00:01","timestamp":"2001-02-03 04:05:06","clob":"𠜎𠜱𠝹𠱓𠱸𠲖𠳏𠳕𠴕𠵼𠵿𠸎𠸏𠹷𠺝𠺢𠻗","blob":"T8O5IGVzdCBsZSBjYWbDqSBsZSBwbHVzIHByb2NoZT8=","geometry":"POINT(1 2)"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "015_update_types_table_AG",
			Method:     http.MethodDelete,
			Uri:        "/columns/types",
			Body:       ``,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_A",
			Method:     http.MethodPost,
			Uri:        "/columns",
			Body:       `{"name":"forgiving","type":"table","columns":[{"name":"id","type":"integer","pk":true},{"name":"integer","type":"integer"},{"name":"bigint","type":"bigint"},{"name":"varchar","type":"varchar","length":10},{"name":"decimal","type":"decimal","precision":10,"scale":4},{"name":"float","type":"float"},{"name":"double","type":"double"},{"name":"boolean","type":"boolean"},{"name":"date","type":"date"},{"name":"time","type":"time"},{"name":"timestamp","type":"timestamp"},{"name":"clob","type":"clob"},{"name":"blob","type":"blob"},{"name":"geometry","type":"geometry"}]}`,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_B",
			Method:     http.MethodPost,
			Uri:        "/records/forgiving",
			Body:       `{"integer":2,"bigint":3,"varchar":"abc","decimal":1.23,"float":1,"double":23.45,"boolean":true,"date":"1970-01-01","time":"00:00:01","timestamp":"2001-02-03 04:05:06","clob":"a","blob":"YQ==","geometry":"POINT(1 2)"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_C",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"boolean":"true"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_D",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=boolean",
			Body:       ``,
			Want:       `{"boolean":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_E",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"boolean":"yes"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_F",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=boolean",
			Body:       ``,
			Want:       `{"boolean":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_G",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"boolean":"1"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_H",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=boolean",
			Body:       ``,
			Want:       `{"boolean":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_I",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"boolean":1}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_J",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=boolean",
			Body:       ``,
			Want:       `{"boolean":true}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_K",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"integer":" 2\n"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_L",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=integer",
			Body:       ``,
			Want:       `{"integer":2}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:          "016_update_forgiving_table_M",
			Method:        http.MethodPut,
			Uri:           "/records/forgiving/1",
			RequestHeader: map[string]string{"Content-Type": "application/x-www-form-urlencoded"},
			Body:          `integer=2%20`,
			Want:          `1`,
			StatusCode:    http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_N",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=integer",
			Body:       ``,
			Want:       `{"integer":2}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_O",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"integer":1.99999}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_P",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=integer",
			Body:       ``,
			Want:       `{"integer":2}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_Q",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"bigint":" 3\n"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_R",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=bigint",
			Body:       ``,
			Want:       `{"bigint":3}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_S",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"bigint":2.99999}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_T",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=bigint",
			Body:       ``,
			Want:       `{"bigint":3}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_U",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"decimal":"1.23"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_V",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=decimal",
			Body:       ``,
			Want:       `{"decimal":"1.2300"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_W",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"decimal":1.2300}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_X",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=decimal",
			Body:       ``,
			Want:       `{"decimal":"1.2300"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_Y",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"decimal":"1.23004"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_Z",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=decimal",
			Body:       ``,
			Want:       `{"decimal":"1.2300"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AA",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"decimal":"1.23006"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AB",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=decimal",
			Body:       ``,
			Want:       `{"decimal":"1.2301"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:          "016_update_forgiving_table_AC",
			Method:        http.MethodPut,
			Uri:           "/records/forgiving/1",
			RequestHeader: map[string]string{"Content-Type": "application/x-www-form-urlencoded"},
			Body:          `float=1%20`,
			Want:          `1`,
			StatusCode:    http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AD",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=float",
			Body:       ``,
			Want:       `{"float":1}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AE",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"double":" 23.45e-1 "}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AF",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=double",
			Body:       ``,
			Want:       `{"double":2.345}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AG",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"date":"2020-12-05"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AH",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=date",
			Body:       ``,
			Want:       `{"date":"2020-12-05"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AI",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"date":"December 20th, 2020"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AJ",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=date",
			Body:       ``,
			Want:       `{"date":"2020-12-20"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AK",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"time":"13:15"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AL",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=time",
			Body:       ``,
			Want:       `{"time":"13:15:00"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AM",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"timestamp":"2012-1-1 23:46"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AN",
			Method:     http.MethodGet,
			Uri:        "/records/forgiving/1?include=timestamp",
			Body:       ``,
			Want:       `{"timestamp":"2012-01-01 23:46:00"}`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AO",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"clob":"𠜎𠜱𠝹𠱓𠱸𠲖𠳏𠳕𠴕𠵼𠵿𠸎𠸏𠹷𠺝𠺢𠻗"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AP",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"blob":"!"}`,
			WantJson:   `{"code":1013,"message":"Input validation failed for 'forgiving'","details":{"blob":"invalid base64"}}`,
			StatusCode: http.StatusUnprocessableEntity,
		},
		{
			Name:       "016_update_forgiving_table_AQ",
			Method:     http.MethodPut,
			Uri:        "/records/forgiving/1",
			Body:       `{"blob":"T8O5IGVzdCBsZSBjYWbDqSBsZSBwbHVzIHByb2NoZT8"}`,
			Want:       `1`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "016_update_forgiving_table_AR",
			Method:     http.MethodDelete,
			Uri:        "/columns/forgiving",
			Body:       ``,
			Want:       `true`,
			StatusCode: http.StatusOK,
		},
		{
			Name:       "017_get_barcodes_table_as_xml",
			Method:     http.MethodGet,
			Uri:        "/columns/barcodes?format=xml",
			Body:       ``,
			Want:       `<root><columns><name>bin</name><type>blob</type></columns><columns><length>255</length><name>hex</name><type>varchar</type></columns><columns><name>id</name><pk>true</pk><type>integer</type></columns><columns><length>15</length><name>ip_address</name><nullable>true</nullable><type>varchar</type></columns><columns><fk>products</fk><name>product_id</name><type>integer</type></columns><name>barcodes</name><type>table</type></root>`,
			StatusCode: http.StatusOK,
		},
	}
	utils.RunTests(t, serverUrlHttps, tt)
	if db_path != "" {
		if err := os.Remove(db_path); err != nil {
			panic(err)
		}
	}
}
