name: Build and test

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

env:
  GO_VERSION: 1.17.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
          args: -D unused -D staticcheck -D gosimple

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: go build -v ./...

    - name: Run vet
      run: go vet ./...
  
  test-sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: go test -v ./...
  
  #Trying https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
  test-postgresql:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        
      - name: Install postgresql-client
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
        
      - name: Create database
        run: | 
          PGPASSWORD=postgres psql -q -h $POSTGRES_HOST -U postgres -f $GITHUB_WORKSPACE/test/sql/create_pgsql.sql
          PGPASSWORD=go-crud-api psql -q -h $POSTGRES_HOST -U go-crud-api -f $GITHUB_WORKSPACE/test/sql/blog_pgsql.sql
        env:
          POSTGRES_HOST: localhost
          PGPORT: 5432

      - name: Run tests
        run: go test -v ./...
        env:
          GCA_CONFIG_FILE: ${{ github.workspace }}/test/yaml/gcaconfig_pgsql.yaml

  test-mysql:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 3306:3306
    
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        
      - name: Install mysql-client
        run: |
          sudo apt-get update
          sudo apt-get install --yes mysql-client
        
      - name: Create database
        run: |
          mysql -uroot < $GITHUB_WORKSPACE/test/sql/create_mysql.sql
          mysql go-crud-api -ugo-crud-api -pgo-crud-api < $GITHUB_WORKSPACE/test/sql/blog_mysql.sql
        env:
          POSTGRES_HOST: localhost
          PGPORT: 3306

      - name: Run tests
        run: go test -v ./...
        env:
          GCA_CONFIG_FILE: ${{ github.workspace }}/test/yaml/gcaconfig_mysql.yaml
