name: Build and test

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

env:
  GO_VERSION: 1.17.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
          args: -D unused -D staticcheck -D gosimple

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: go build -v ./...

    - name: Run vet
      run: go vet ./...
  
  test-sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: go test -v ./...
  
  #Trying https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
  test-postgresql:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        
      - name: Install postgresql-client
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
        
      - name: Create database
        run: | 
          PGPASSWORD=postgres psql -q -h $POSTGRES_HOST -U postgres -f $GITHUB_WORKSPACE/test/sql/create_pgsql.sql
          PGPASSWORD=go-crud-api psql -q -h $POSTGRES_HOST -U go-crud-api -f $GITHUB_WORKSPACE/test/sql/blog_pgsql.sql
        env:
          POSTGRES_HOST: localhost
          PGPORT: 5432

      - name: Run tests
        run: go test -v ./...
        env:
          GCA_CONFIG_FILE: ${{ github.workspace }}/test/yaml/gcaconfig_pgsql.yaml

  test-mysql:
    runs-on: ubuntu-latest
    
    services:
      mysqldb:
        image: mysql:latest
        ports:
        - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        
      - name: Install mysql-client
        run: |
          sudo apt-get update
          sudo apt-get install --yes mysql-client-core-8.0
       
      - name: Create database
        run: |
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -uroot < $GITHUB_WORKSPACE/test/sql/create_mysql.sql
          mysql go-crud-api -h $MYSQL_HOST -P $MYSQL_PORT -ugo-crud-api -pgo-crud-api < $GITHUB_WORKSPACE/test/sql/blog_mysql.sql
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: ${{ job.services.mysqldb.ports['3306'] }}

      - name: Run tests
        run: go test -v ./...
        env:
          GCA_CONFIG_FILE: ${{ github.workspace }}/test/yaml/gcaconfig_mysql.yaml
          GCA_API_PORT: ${{ job.services.mysqldb.ports['3306'] }}

  test-sqlserver:
    runs-on: ubuntu-latest
    
    services:
      sqlserverdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "mystrongPasw0rd!"
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -U sa -P ${SA_PASSWORD} -Q \"SELECT \"READY\"\" | grep -q \"READY\""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        
      - name: Install mssql-tools
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --yes mssql-tools unixodbc-dev
       
      - name: Create database
        run: |
          /opt/mssql-tools/bin/sqlcmd -S $MSSQL_HOST,$MSSQL_PORT -U sa -P mystrongPasw0rd! -i $GITHUB_WORKSPACE/test/sql/create_sqlsrv.sql
          /opt/mssql-tools/bin/sqlcmd -S $MSSQL_HOST,$MSSQL_PORT -U go-crud-api -P go-crud-api -i $GITHUB_WORKSPACE/test/sql/blog_sqlsrv.sql
        env:
          MSSQL_HOST: 127.0.0.1
          MSSQL_PORT: ${{ job.services.sqlserverdb.ports['1433'] }}

      - name: Run tests
        run: go test -v ./...
        env:
          GCA_CONFIG_FILE: ${{ github.workspace }}/test/yaml/gcaconfig_sqlsrv.yaml
          GCA_API_PORT: ${{ job.services.sqlserverdb.ports['1433'] }}
